FROM node:24-alpine3.21 AS development

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY index.html vite.config.js ./
COPY public ./public
COPY src ./src

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
