
CREATE TABLE IF NOT EXISTS course (
 id BIGSERIAL PRIMARY KEY ,
 title VARCHAR(225) NOT NULL UNIQUE ,
 description VARCHAR(255) NOT NULL,
 fee DECIMAL(10,2) NOT NULL ,
    capacity INTEGER NOT NULL ,
  created_at  DATE NOT NULL  DEFAULT CURRENT_DATE
);