
ALTER TABLE course ADD COLUMN start_date DATE NOT NULL default CURRENT_DATE ;
ALTER TABLE course ADD COLUMN end_date DATE NOT NULL DEFAULT CURRENT_DATE;

ALTER TABLE course ADD COLUMN  is_visible BOOLEAN NOT NULL DEFAULT FALSE;