-- 1. Create the Parent Table (CourseCategory)
CREATE TABLE course_category (
                                 category_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 code VARCHAR(255) NOT NULL,
                                 name VARCHAR(255) NOT NULL,
                                 description VARCHAR(255) NOT NULL,
                                 created_at TIMESTAMP NOT NULL,
                                 CONSTRAINT pk_course_category PRIMARY KEY (category_id),
                                 CONSTRAINT uq_course_category_code UNIQUE (code)
);

-- 2. Create the Child Table (Course) with Foreign Key Connection
CREATE TABLE course (
                        course_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        course_code VARCHAR(255) NOT NULL,
                        course_name VARCHAR(255) NOT NULL,
                        description VARCHAR(255) NOT NULL,
                        objectives VARCHAR(255) NOT NULL,
                        target_audience VARCHAR(255) NOT NULL,
                        pre_request VARCHAR(255) NOT NULL,
                        duration_value NUMERIC(38, 2) NOT NULL,
                        duration_unit VARCHAR(255) NOT NULL,
                        training_hours NUMERIC(38, 2) NOT NULL,
                        deliverable_mode VARCHAR(255) NOT NULL,
                        default_fee NUMERIC(38, 2) NOT NULL,
                        certificate_policy VARCHAR(255) NOT NULL,
                        pass_mark NUMERIC(38, 2) NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        category_id BIGINT,
                        CONSTRAINT pk_course PRIMARY KEY (course_id),
                        CONSTRAINT uq_course_code UNIQUE (course_code),
                        CONSTRAINT fk_course_category FOREIGN KEY (category_id) REFERENCES course_category (category_id)
);

