-- 1. Create Course Intakes Table
CREATE TABLE IF NOT EXISTS course_intakes (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                course_id BIGINT NOT NULL,
                                intake_code VARCHAR(255) NOT NULL,
                                name VARCHAR(255) NOT NULL,
                                start_date DATE,
                                end_date DATE,
                                registration_deadline DATE,
                                delivery_mode VARCHAR(255),
                                fee NUMERIC(38, 2),
                                online_meeting_url VARCHAR(255),
                                capacity INTEGER,
                                minimum_enrollment INTEGER,
                                location VARCHAR(255),
                                status VARCHAR(255),
                                created_at TIMESTAMP,
                                updated_at TIMESTAMP,
                                CONSTRAINT pk_course_intakes PRIMARY KEY (id),
                                CONSTRAINT uq_intake_code UNIQUE (intake_code),
                                CONSTRAINT fk_intakes_course FOREIGN KEY (course_id) REFERENCES course (course_id)
);

-- 2. Create Intake Instructors Bridge Table
CREATE TABLE intake_instructors (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    intake_id BIGINT NOT NULL,
                                    instructor_id BIGINT NOT NULL,
                                    role VARCHAR(255),
                                    assigned_at TIMESTAMP,
                                    CONSTRAINT pk_intake_instructors PRIMARY KEY (id),
                                    CONSTRAINT fk_instructors_intake FOREIGN KEY (intake_id) REFERENCES course_intakes (id) ON DELETE CASCADE

);
