-- 1. Create Applications Table
CREATE TABLE IF NOT EXISTS applications (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                            student_id BIGINT NOT NULL,
                                            intake_id BIGINT NOT NULL,
                                            application_number VARCHAR(255) NOT NULL,
                                            application_date DATE,
                                            status VARCHAR(50) NOT NULL,
                                            submitted_at TIMESTAMP,
                                            reviewed_at TIMESTAMP,
                                            reviewed_by BIGINT,
                                            rejection_reason TEXT,
                                            created_at TIMESTAMP,
                                            updated_at TIMESTAMP,
                                            CONSTRAINT pk_applications PRIMARY KEY (id),
                                            CONSTRAINT uq_application_number UNIQUE (application_number),
                                            CONSTRAINT fk_applications_intake FOREIGN KEY (intake_id) REFERENCES course_intakes (id),
                                            CONSTRAINT fk_applications_student FOREIGN KEY (student_id) REFERENCES student (student_id),
                                            CONSTRAINT fk_applications_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id)
);

-- 2. Create Waiting Lists Table
CREATE TABLE IF NOT EXISTS waiting_lists (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                             student_id BIGINT NOT NULL,
                                             intake_id BIGINT NOT NULL,
                                             application_id BIGINT,
                                             position INTEGER,
                                             status VARCHAR(50) NOT NULL,
                                             added_at TIMESTAMP,
                                             removed_at TIMESTAMP,
                                             CONSTRAINT pk_waiting_lists PRIMARY KEY (id),
                                             CONSTRAINT fk_waiting_lists_student FOREIGN KEY (student_id) REFERENCES student (student_id),
                                             CONSTRAINT fk_waiting_lists_intake FOREIGN KEY (intake_id) REFERENCES course_intakes (id),
                                             CONSTRAINT fk_waiting_lists_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE SET NULL
);