-- 1. Create Application Documents Table
CREATE TABLE IF NOT EXISTS application_documents (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                                     application_id BIGINT NOT NULL,
                                                     document_type VARCHAR(100),
                                                     file_name VARCHAR(255) NOT NULL,
                                                     file_path TEXT NOT NULL,
                                                     mime_type VARCHAR(100),
                                                     file_size BIGINT,
                                                     status VARCHAR(50) NOT NULL,
                                                     verification_notes TEXT,
                                                     verified_by BIGINT,
                                                     uploaded_at TIMESTAMP,
                                                     verified_at TIMESTAMP,
                                                     CONSTRAINT pk_application_documents PRIMARY KEY (id),
                                                     CONSTRAINT fk_documents_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE,
                                                     CONSTRAINT fk_documents_verifier FOREIGN KEY (verified_by) REFERENCES users (id)
);

-- 2. Create Enrollments Table
CREATE TABLE IF NOT EXISTS enrollments (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                           student_id BIGINT NOT NULL,
                                           intake_id BIGINT NOT NULL,
                                           application_id BIGINT,
                                           enrollment_number VARCHAR(255) NOT NULL,
                                           status VARCHAR(50) NOT NULL,
                                           completion_status VARCHAR(50) NOT NULL,
                                           enrolled_at TIMESTAMP,
                                           completed_at TIMESTAMP,
                                           created_at TIMESTAMP,
                                           updated_at TIMESTAMP,
                                           CONSTRAINT pk_enrollments PRIMARY KEY (id),
                                           CONSTRAINT uq_enrollment_number UNIQUE (enrollment_number),
                                           CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES student (student_id),
                                           CONSTRAINT fk_enrollments_intake FOREIGN KEY (intake_id) REFERENCES course_intakes (id),
                                           CONSTRAINT fk_enrollments_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE SET NULL
);

-- 3. Create Sessions Table
CREATE TABLE IF NOT EXISTS sessions (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                        intake_id BIGINT NOT NULL,
                                        instructor_id BIGINT,
                                        session_date DATE NOT NULL,
                                        start_time TIME NOT NULL,
                                        end_time TIME NOT NULL,
                                        delivery_mode VARCHAR(50),
                                        location VARCHAR(255),
                                        online_details TEXT,
                                        status VARCHAR(50) NOT NULL,
                                        created_at TIMESTAMP,
                                        updated_at TIMESTAMP,
                                        CONSTRAINT pk_sessions PRIMARY KEY (id),
                                        CONSTRAINT fk_sessions_intake FOREIGN KEY (intake_id) REFERENCES course_intakes (id),
                                        CONSTRAINT fk_sessions_instructor FOREIGN KEY (instructor_id) REFERENCES instructor (instructor_id)
);

-- 4. Create Attendance Table
CREATE TABLE IF NOT EXISTS attendance (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                          session_id BIGINT NOT NULL,
                                          enrollment_id BIGINT NOT NULL,
                                          attendance_status VARCHAR(50) NOT NULL,
                                          attendance_time TIMESTAMP,
                                          remarks VARCHAR(255),
                                          recorded_by BIGINT,
                                          created_at TIMESTAMP,
                                          updated_at TIMESTAMP,
                                          CONSTRAINT pk_attendance PRIMARY KEY (id),
                                          CONSTRAINT fk_attendance_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
                                          CONSTRAINT fk_attendance_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments (id),
                                          CONSTRAINT fk_attendance_recorder FOREIGN KEY (recorded_by) REFERENCES users (id)
);